### ISSUE TITLE
Missing Space

### ISSUE THREAD

**Issue by Leinad4Mind** [VSEphpbb/TopicImagePreview#4]
https://github.com/VSEphpbb/TopicImagePreview/blob/817703a35aa346eb28006ec6d1a359a204670c85/styles/all/template/event/topiclist_row_prepend.html#L16

Wrong position space?

`<div {% if preview.TOPIC_IMAGES %}data-ot`

Shouldnt be?: `<div{% if preview.TOPIC_IMAGES %} data-ot`

**Comment by VSEphpbb** [comment]
Yes

**Comment by Leinad4Mind** [comment]
Btw, shouldnt the extension name folder in vse/extension_name be lowercase?
https://github.com/VSEphpbb/TopicImagePreview/blob/master/composer.json#L2
